# Generated by Django 3.1.4 on 2021-05-11 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comdition',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Comdition name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.material', verbose_name='Material name'),
        ),
        migrations.AddField(
            model_name='product',
            name='wire',
            field=models.CharField(default='false', max_length=50, verbose_name='Wire name'),
            preserve_default=False,
        ),
    ]
