# Generated by Django 3.1.4 on 2021-05-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210511_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='1 year', max_length=50, verbose_name='Warranty'),
            preserve_default=False,
        ),
    ]
